export default [
  {
    id: 1,
    title: "Noxus",
    location: "Valoran (East)",
    type: "Expansionist Empire",
    description:
      "Noxus is a powerful empire with a fearsome reputation. To those beyond its borders, Noxus is brutal, expansionist, and threatening, yet those who look beyond its warlike exterior see an unusually inclusive society, where the strengths and talents of its people are respected and cultivated.",
    iconUrl: "icons/Noxus_Crest_icon.png",
    imageUrl: "images/Noxus_The_Immortal_Bastion_01.jpg",
    champions: {
      0: { name: "Draven" },
      1: { name: "Darius" },
      2: { name: "Cassiopeia" },
      3: { name: "Katarina" },
      4: { name: "Kled" },
      5: { name: "Leblanc" },
      6: { name: "Rell" },
      7: { name: "Riven" },
      8: { name: "Samira" },
      9: { name: "Sion" },
      10: { name: "Swain" },
      11: { name: "Talon" },
      12: { name: "Vladimir" },
    },
  },
  {
    id: 2,
    title: "Demacia",
    location: "Valoran (West)",
    type: "Feudal Monarchy",
    description:
      "A strong, lawful kingdom with a prestigious military history, Demacia's people have always valued the ideals of justice, honor, and duty most highly, and are fiercely proud of their cultural heritage.",
    iconUrl: "icons/Demacia_Crest_icon.png",
    imageUrl: "images/Demacia.jpg",
    champions: {
      0: { name: "Fiora" },
      1: { name: "Galio" },
      2: { name: "Garen" },
      3: { name: "Jarvan IV" },
      4: { name: "Kayle" },
      5: { name: "Lucian" },
      6: { name: "Lux" },
      7: { name: "Morgana" },
      8: { name: "Poppy" },
      9: { name: "Quinn" },
      10: { name: "Shyvana" },
      11: { name: "Sona" },
      12: { name: "Sylas" },
      13: { name: "Vayne" },
      14: { name: "XinZhao" },
    },
  },
  {
    id: 4,
    title: "Freljord",
    location: "Valoran (North)",
    type: "Tribal Matriarchy",
    description:
      "The Freljord is a harsh and unforgiving land. Proud and fiercely independent, its people are born warriors, with a strong raiding culture. While there are many individual tribes within the Freljord, the battle lines are being drawn in a three-way civil war that will determine the future of them all.",
    iconUrl: "icons/Freljord_Crest_icon.png",
    imageUrl: "images/Freljord.jpg",
    champions: {
      0: { name: "Anivia" },
      1: { name: "Ashe" },
      2: { name: "Braum" },
      3: { name: "Gnar" },
      4: { name: "Gragas" },
      5: { name: "Lissandra" },
      6: { name: "Nunu" },
      7: { name: "Olaf" },
      8: { name: "Ornn" },
      9: { name: "Sejuani" },
      10: { name: "Trundle" },
      11: { name: "Tryndamere" },
      12: { name: "Udyr" },
      13: { name: "Volibear" },
    },
  },
  {
    id: 5,
    title: "Zaun",
    location: "Valoran (South)",
    type: "Industrial Oligarchy",
    description:
      "Zaun, also known as the City of Iron and Glass, is a large, undercity district, lying in the deep canyons and valleys threading Piltover. What light reaches below is filtered through fumes leaking from the tangles of corroded pipework and reflected from the stained glass of its industrial architecture.",
    iconUrl: "icons/Zaun_Crest_icon.png",
    imageUrl: "images/Zaun.jpg",
    champions: {
      0: { name: "Blitzcrank" },
      1: { name: "DrMundo" },
      2: { name: "Ekko" },
      3: { name: "Janna" },
      4: { name: "Jinx" },
      5: { name: "Singed" },
      6: { name: "Twitch" },
      7: { name: "Urgot" },
      8: { name: "Viktor" },
      9: { name: "Warwick" },
      10: { name: "Zac" },
      11: { name: "Zeri" },
      12: { name: "Ziggs" },
    },
  },
  {
    id: 6,
    title: "Piltover",
    location: "Valoran (South)",
    type: "Aristocratic Oligarchy",
    description:
      "Piltover, also known as the City of Progress, is a thriving, progressive city whose power and influence is on the rise. It is Valoran's cultural center, where art, craftsmanship, trade and innovation walk hand in hand. Its power comes not through military might, but the engines of commerce and forward thinking. ",
    iconUrl: "icons/Piltover_Crest_icon.png",
    imageUrl: "images/Piltover.jpg",
    champions: {
      0: { name: "Caitlyn" },
      1: { name: "Camille" },
      2: { name: "Ezreal" },
      3: { name: "Heimerdinger" },
      4: { name: "Jayce" },
      5: { name: "Orianna" },
      6: { name: "Seraphine" },
      7: { name: "Vi" },
    },
  },
  {
    id: 7,
    title: "Targon",
    location: "Shurima (West)",
    type: "Tribal Theocracy",
    description:
      "Like any place of myth, Mount Targon is a beacon to dreamers, madmen and questors of adventure. A mountainous and sparsely inhabited region to the west of Shurima, Targon boasts the tallest peak in Runeterra. Located far from civilization, Mount Targon is all but impossible to reach, save by the most determined pilgrims, chasing some soul-deep yearning to reach its summit. ",
    iconUrl: "icons/Mount_Targon_Crest_icon.png",
    imageUrl: "images/Targon.jpg",
    champions: {
      0: { name: "Aphelios" },
      1: { name: "Diana" },
      2: { name: "Leona" },
      3: { name: "Pantheon" },
      4: { name: "Soraka" },
      5: { name: "Taric" },
      6: { name: "Zoe" },
    },
  },
  {
    id: 8,
    title: "Shurima",
    location: "Shurima (Center)",
    type: "Divine Empire",
    description:
      "The empire of Shurima was once a thriving civilization that spanned a vast desert. After an era of growth and prosperity, the fall fall of its gleaming capital left the empire in ruins. Over millennia, tales of Shurima's glorious city became myth and religion among the descendants of the scattered survivors.",
    iconUrl: "icons/Shurima_Crest_icon.png",
    imageUrl: "images/Shurima.jpg",
    champions: {
      0: { name: "Akshan" },
      1: { name: "Amumu" },
      2: { name: "Azir" },
      3: { name: "Nasus" },
      4: { name: "Rammus" },
      5: { name: "Renekton" },
      6: { name: "Sivir" },
      7: { name: "Skarner" },
      8: { name: "Taliyah" },
      9: { name: "Xerath" },
    },
  },
  {
    id: 9,
    title: "Ionia",
    location: "Ionia",
    type: "Regional Provinces",
    description:
      "Ionia, in original Vastayan nomenclature: The First Lands, is a land of unspoiled beauty and natural magic. Its inhabitants, living in scattered settlements across this massive archipelago, are a spiritual people who seek to live in harmony and balance with the world. There are many orders and sects across Ionia, each following their own (often conflicting) paths and ideals.",
    iconUrl: "icons/Ionia_Crest_icon.png",
    imageUrl: "images/Ionia.jpg",
    champions: {
      0: { name: "Ahri" },
      1: { name: "Akali" },
      2: { name: "Irelia" },
      3: { name: "Ivern" },
      4: { name: "Jhin" },
      5: { name: "Karma" },
      6: { name: "Kayn" },
      7: { name: "Kennen" },
      8: { name: "LeeSin" },
      9: { name: "Lillia" },
      10: { name: "MasterYi" },
      11: { name: "Rakan" },
      12: { name: "Sett" },
      13: { name: "Shen" },
      14: { name: "Syndra" },
      15: { name: "Varus" },
      16: { name: "Wukong" },
      17: { name: "Xayah" },
      18: { name: "Yasuo" },
      19: { name: "Yone" },
      20: { name: "Zed" },
    },
  },
  {
    id: 10,
    title: "Shadow Isles",
    location: "Guardian's Sea",
    type: "Former Meritocracy",
    description:
      "The land now known as the Shadow Isles was once a beautiful realm, but it was shattered by a magical cataclysm. Black Mist permanently shrouds the isles and the land itself is tainted, corrupted by malevolent sorcery sorcery. Living beings that stand upon the Shadow Isles slowly have their life-force leeched from them, which, in turn, draws the insatiable, predatory spirits of the dead. ",
    iconUrl: "icons/Shadow_Isles_Crest_icon.png",
    imageUrl: "images/Blessed_Isles.jpg",
    champions: {
      0: { name: "Elise" },
      1: { name: "Gwen" },
      2: { name: "Hecarim" },
      3: { name: "Kalista" },
      4: { name: "Karthus" },
      5: { name: "Maokai" },
      6: { name: "Mordekaiser" },
      7: { name: "Thresh" },
      8: { name: "Viego" },
      9: { name: "Yorick" },
    },
  },
  {
    id: 11,
    title: "Bilgewater",
    location: "Guardian's Sea",
    type: "Gang Syndicates",
    description:
      "Bilgewater is a haven for smugglers, marauders, and the unscrupulous, where fortunes are made and ambitions shattered in the blink of an eye. For those fleeing justice, debt, or persecution, it is a city of new beginnings; no one on the twisted streets of Bilgewater cares about your past. It's a melting pot of cultures, races, and creeds, alive with activity at all hours.",
    iconUrl: "icons/Bilgewater_Crest_icon.png",
    imageUrl: "images/Bilgewater.jpg",
    champions: {
      0: { name: "Gangplank" },
      1: { name: "Graves" },
      2: { name: "Illaoi" },
      3: { name: "MissFortune" },
      4: { name: "Nautilus" },
      5: { name: "Pyke" },
      6: { name: "TwistedFate" },
    },
  },
  {
    id: 12,
    title: "Ixtal",
    location: "Shurima (East)",
    type: "Mage Autocracy",
    description:
      "Renowned for its mastery of elemental magic, Ixtal was one of the first independent nations to join the Shuriman empire. In truth, Ixtali culture is much older—part of the great westward diaspora that gave rise to civilizations including the Buhru, magnificent Helia, and the ascetics of Targon—and it is likely they played a significant role in the creation of the first Ascended.",
    iconUrl: "icons/Ixtal_Crest_icon.png",
    imageUrl: "images/Ixtal.jpg",
    champions: {
      0: { name: "Malphite" },
      1: { name: "Neeko" },
      2: { name: "Nidalee" },
      3: { name: "Qiyana" },
      4: { name: "Rengar" },
      5: { name: "Zyra" },
    },
  },
  {
    id: 13,
    title: "Bandle City",
    location: "Location unkown",
    description:
      "Opinions differ as to where exactly the home of the yordles is to be found, though a handful of mortals claim to have traveled unseen pathways to a land of curious enchantment beyond the material realm. They tell of a place of unfettered magic, where the foolhardy can be led astray by myriad wonders, and end up lost in a dream...",
    iconUrl: "icons/Bandle_City_Crest_icon.png",
    imageUrl: "images/Bandle_City.jpg",
    champions: {
      0: { name: "Corki" },
      1: { name: "Lulu" },
      2: { name: "Rumble" },
      3: { name: "Teemo" },
      4: { name: "Tristana" },
      5: { name: "Veigar" },
      6: { name: "Vex" },
      7: { name: "Yuumi" },
    },
  },
];
