export default [
  {
    id: 1,
    title: "Noxus",
    location: "Valoran (East)",
    type: "Expansionist Empire",
    description: [
      "Noxus is a city in the eastern part of Valoran. It is the capital of the Noxian Empire, which is the largest empire in the world. It is located in the southern part of the continent, and is the largest city in the continent. Noxus is the largest city in the world, and the second largest city in the world after the capital of the Noxian Empire, which is located in the southern part of the continent.",
      "Noxus ist eine Stadt im östlichen Teil von Valoran. Es ist die Hauptstadt der Noxian-Emperie, die die größte Emperie der Welt ist. Sie ist im südlichen Teil der Kontinent und die zweitgrößte Stadt in der Kontinent. Noxus ist die größte Stadt der Welt und die zweitgrößte Stadt in der Welt nach der Hauptstadt der Noxian-Emperie, die sich im südlichen Teil der Kontinent befindet.",
      "Noxus é uma cidade na parte ocidental da Valoran. É a capital da Emperie Noxiana, que é a maior emperie do mundo. Ela está localizada na parte sul do continente, e é a segunda maior cidade do continente. Noxus é a maior cidade do mundo e a segunda maior cidade do mundo após a capital da Emperie Noxiana, que está localizada na parte sul do continente.",
    ],
    iconUrl: "icons/Noxus_Crest_icon.png",
    imageUrl: "images/Noxus.jpg",
    wallpapers: {
      0: {
        title: "Noxian Army",
        url: "regions/Noxus_00.jpg",
      },
      1: {
        title: "The Immortal Bastion",
        url: "regions/Noxus_01.jpg",
      },
      2: {
        title: "Noxian Ship",
        url: "regions/Noxus_02.png",
      },
    },
    champions: {
      0: {
        name: "Draven",
        skins: {
          0: {
            splashUrl: "images/splash/Draven_0.jpg",
            description: "Draven The glorious executioner",
          },
          1: {
            splashUrl: "images/splash/Draven_1.jpg",
            description: "Soul Reaver Draven",
          },
          2: {
            splashUrl: "images/splash/Draven_2.jpg",
            description: "Gladiator Draven",
          },
          3: {
            splashUrl: "images/splash/Draven_3.jpg",
            description: "Primetime Draven",
          },
          4: {
            splashUrl: "images/splash/Draven_4.jpg",
            description: "Pool Party Draven",
          },
          5: {
            splashUrl: "images/splash/Draven_5.jpg",
            description: "Beast Hunter Draven",
          },
          6: {
            splashUrl: "images/splash/Draven_6.jpg",
            description: "Draven Draven",
          },
          7: {
            splashUrl: "images/splash/Draven_7.jpg",
            description: "Santa Draven",
          },
          8: {
            splashUrl: "images/splash/Draven_8.jpg",
            description: "Mecha Kingdoms Draven",
          },
          9: {
            splashUrl: "images/splash/Draven_9.jpg",
            description: "Ruined Draven",
          },
          10: {
            splashUrl: "images/splash/Draven_10.jpg",
            description: "Debonair Draven",
          },
        },
      },
      1: {
        name: "Darius",
        skins: {
          0: {
            splashUrl: "images/splash/Darius_0.jpg",
            description: "Darius The Hand of Noxus",
          },
          1: {
            splashUrl: "images/splash/Darius_1.jpg",
            description: "Lord Darius",
          },
          2: {
            splashUrl: "images/splash/Darius_2.jpg",
            description: "Bioforge Darius",
          },
          3: {
            splashUrl: "images/splash/Darius_3.jpg",
            description: "Woad King Darius",
          },
          4: {
            splashUrl: "images/splash/Darius_4.jpg",
            description: "Dunkmaster Darius",
          },
          5: {
            splashUrl: "images/splash/Darius_8.jpg",
            description: "Academy Darius",
          },
          6: {
            splashUrl: "images/splash/Darius_14.jpg",
            description: "Dreadnova Darius",
          },
          7: {
            splashUrl: "images/splash/Darius_15.jpg",
            description: "God King Darius",
          },
          8: {
            splashUrl: "images/splash/Darius_16.jpg",
            description: "High Noon Darius",
          },
          9: {
            splashUrl: "images/splash/Darius_24.jpg",
            description: "Lunar Beast Darius",
          },
          10: {
            splashUrl: "images/splash/Darius_33.jpg",
            description: "Crime City Nightmare Darius",
          },
        },
      },
      2: {
        name: "Cassiopeia",
        nick: "The Serpent's Embrace",
        skins: {
          0: {
            splashUrl: "images/splash/Cassiopeia_0.jpg",
            description: "Cassiopeia The Serpent's Embrace",
          },
          1: {
            splashUrl: "images/splash/Cassiopeia_1.jpg",
            description: "Desperada Cassiopeia",
          },
          2: {
            splashUrl: "images/splash/Cassiopeia_2.jpg",
            description: "Siren Cassiopeia",
          },
          3: {
            splashUrl: "images/splash/Cassiopeia_3.jpg",
            description: "Mythic Cassiopeia",
          },
          4: {
            splashUrl: "images/splash/Cassiopeia_4.jpg",
            description: "Jade Fang Cassiopeia",
          },
          5: {
            splashUrl: "images/splash/Cassiopeia_8.jpg",
            description: "Eternum Cassiopeia",
          },
          6: {
            splashUrl: "images/splash/Cassiopeia_9.jpg",
            description: "Spirit Blossom Cassiopeia",
          },
          7: {
            splashUrl: "images/splash/Cassiopeia_18.jpg",
            description: "Coven Cassiopeia",
          },
        },
      },
      3: {
        name: "Katarina",
        nick: "The Sinister Blade",
        skins: {
          0: {
            splashUrl: "images/splash/Katarina_0.jpg",
            description: "Katarina The Sinister Blade",
          },
          1: {
            splashUrl: "images/splash/Katarina_1.jpg",
            description: "Mercenary Katarina",
          },
          2: {
            splashUrl: "images/splash/Katarina_2.jpg",
            description: "Red Card Katarina",
          },
          3: {
            splashUrl: "images/splash/Katarina_3.jpg",
            description: "Bilgewater Katarina",
          },
          4: {
            splashUrl: "images/splash/Katarina_4.jpg",
            description: "Kitty Cat Katarina",
          },
          5: {
            splashUrl: "images/splash/Katarina_5.jpg",
            description: "High Command Katarina",
          },
          6: {
            splashUrl: "images/splash/Katarina_6.jpg",
            description: "Sandstorm Katarina",
          },
          7: {
            splashUrl: "images/splash/Katarina_7.jpg",
            description: "Slay Belle Katarina",
          },
          8: {
            splashUrl: "images/splash/Katarina_8.jpg",
            description: "Warring Kingdoms Katarina",
          },
          9: {
            splashUrl: "images/splash/Katarina_9.jpg",
            description: "PROJECT: Katarina",
          },
          10: {
            splashUrl: "images/splash/Katarina_10.jpg",
            description: "Death Sworn Katarina",
          },
          11: {
            splashUrl: "images/splash/Katarina_12.jpg",
            description: "Battle Academia Katarina",
          },
          12: {
            splashUrl: "images/splash/Katarina_21.jpg",
            description: "Blood Moon Katarina",
          },
          13: {
            splashUrl: "images/splash/Katarina_29.jpg",
            description: "Battle Queen Katarina",
          },
        },
      },
      4: {
        name: "Kled",
        nick: "The Cantankerous Cavalier",
        skins: {
          0: {
            splashUrl: "images/splash/Kled_0.jpg",
            description: "Kled The Cantankerous Cavalier",
          },
          1: {
            splashUrl: "images/splash/Kled_1.jpg",
            description: "Sir Kled",
          },
          2: {
            splashUrl: "images/splash/Kled_2.jpg",
            description: "Count Kledula",
          },
          3: {
            splashUrl: "images/splash/Kled_9.jpg",
            description: "Marauder Kled",
          },
        },
      },
      5: { name: "Leblanc", nick: "The Deceiver" },
      6: { name: "Rell", nick: "The Iron Maiden" },
      7: { name: "Riven", nick: "The Exile" },
      8: { name: "Samira", nick: "The Desert rose" },
      9: { name: "Sion", nick: "The Undead Juggernaut" },
      10: { name: "Swain", nick: "The Noxian Grand General" },
      11: { name: "Talon", nick: "The Blade's Shadow" },
      12: { name: "Vladimir", nick: "The Crimson Reaper" },
    },
  },
  {
    id: 2,
    title: "Demacia",
    location: "Valoran (West)",
    type: "Feudal Monarchy",
    description: [
      "A strong, lawful kingdom with a prestigious military history, Demacia's people have always valued the ideals of justice, honor, and duty most highly, and are fiercely proud of their cultural heritage.",
      "Eine stark, rechtfertigte Königreich mit einer hervorragenden Militärgeschichte, die dem Volk jüngst die Ideen der Gerechtigkeit, Ehre und Aufgabe am höchsten gewöhnen und sie sind stolz auf ihre kulturelle Herkunft.",
      "Uma grande, justa região com uma história militar prestigiosa, a população de Demacia sempre valorizou os ideias da justiça, honra e obrigação mais importantes, e são fervorosamente orgulhosos de sua herança cultural.",
    ],
    iconUrl: "icons/Demacia_Crest_icon.png",
    imageUrl: "images/Demacia.jpg",
    wallpapers: {
      0: {
        title: "Demacian Army",
        url: "regions/Demacia_00.jpg",
      },
      1: {
        title: "The Grand Plaza of Demacia ",
        url: "regions/Demacia_01.jpg",
      },
      2: {
        title: "Temple of the lightbringers",
        url: "regions/Demacia_02.jpg",
      },
    },
    champions: {
      0: { name: "Fiora" },
      1: { name: "Galio" },
      2: { name: "Garen" },
      3: { name: "Jarvan IV" },
      4: { name: "Kayle" },
      5: { name: "Lucian" },
      6: { name: "Lux" },
      7: { name: "Morgana" },
      8: { name: "Poppy" },
      9: { name: "Quinn" },
      10: { name: "Shyvana" },
      11: { name: "Sona" },
      12: { name: "Sylas" },
      13: { name: "Vayne" },
      14: { name: "XinZhao" },
    },
  },
  {
    id: 3,
    title: "Freljord",
    location: "Valoran (North)",
    type: "Tribal Matriarchy",
    description: [
      "The Freljord is a harsh and unforgiving land. Proud and fiercely independent, its people are born warriors, with a strong raiding culture. While there are many individual tribes within the Freljord, the battle lines are being drawn in a three-way civil war that will determine the future of them all.",
      "Der Freljord ist ein hartes und ungerechtfertigtes Land. Stolz und ständig unabhängig, werden seine Menschen geworden, mit einer starken Beute-Kultur. Obwohl es viele einzelne Stämme im Freljord gibt, wird die Schlacht in einem Drei-Wege-Zivil-Krieg gezeichnet, der die Zukunft aller wird.",
      "Freljord é um terreno feroz e indiferente. Proud e forte independente, sua população é uma raça de guerreiros, com uma cultura de raideamento forte. Enquanto há muitas tribos individuais no Freljord, as linhas de batalha são desenhadas em uma guerra civil que determinará o futuro deles todos.",
    ],
    iconUrl: "icons/Freljord_Crest_icon.png",
    imageUrl: "images/Freljord.jpg",
    wallpapers: {
      0: {
        title: "The Pilgrim Site of Rakelstake",
        url: "regions/Freljord_00.jpg",
      },
      1: {
        title: "Vaults of the Iceborn Beneath Frosthorn Peak",
        url: "regions/Freljord_01.jpg",
      },
      2: {
        title: "Harbor of Glaseport",
        url: "regions/Freljord_02.jpg",
      },
    },
    champions: {
      0: { name: "Anivia" },
      1: { name: "Ashe" },
      2: { name: "Braum" },
      3: { name: "Gnar" },
      4: { name: "Gragas" },
      5: { name: "Lissandra" },
      6: { name: "Nunu" },
      7: { name: "Olaf" },
      8: { name: "Ornn" },
      9: { name: "Sejuani" },
      10: { name: "Trundle" },
      11: { name: "Tryndamere" },
      12: { name: "Udyr" },
      13: { name: "Volibear" },
    },
  },
  {
    id: 4,
    title: "Zaun",
    location: "Valoran (South)",
    type: "Industrial Oligarchy",
    description: [
      "Zaun, also known as the City of Iron and Glass, is a large, undercity district, lying in the deep canyons and valleys threading Piltover. What light reaches below is filtered through fumes leaking from the tangles of corroded pipework and reflected from the stained glass of its industrial architecture.",
      "Zaun, auch bekannt als die Stadt des Eisens und Glas, liegt in den tiefen Kanälen und Talen, die Piltover verlaufen. Wie das Licht, das sich von der Spülung der verbrannten Kabel und der gestrichelten Glas von ihrer industriellen Architektur abfließt.",
      "Zaun, também conhecido como a Cidade de Aço e de Cristal, está localizada em canyons e vales profundos, que se ligam a Piltover. O que luz é filtrado por fumos que se derramam das entranhas de corroídos tubos de tubulação e refletido da estampa de cristais de sua arquitetura industrial.",
    ],
    iconUrl: "icons/Zaun_Crest_icon.png",
    imageUrl: "images/Zaun.jpg",
    wallpapers: {
      0: {
        title: "Boundary Markets",
        url: "regions/Zaun_00.jpg",
      },
      1: {
        title: "Backstreet Hextech Deals",
        url: "regions/Zaun_01.jpg",
      },
      2: {
        title: "Zaun's Depths",
        url: "regions/Zaun_02.jpg",
      },
    },
    champions: {
      0: { name: "Blitzcrank" },
      1: { name: "DrMundo" },
      2: { name: "Ekko" },
      3: { name: "Janna" },
      4: { name: "Jinx" },
      5: { name: "Renata Glasc" },
      6: { name: "Singed" },
      7: { name: "Twitch" },
      8: { name: "Urgot" },
      9: { name: "Viktor" },
      10: { name: "Warwick" },
      11: { name: "Zac" },
      12: { name: "Zeri" },
      13: { name: "Ziggs" },
    },
  },
  {
    id: 5,
    title: "Piltover",
    location: "Valoran (South)",
    type: "Aristocratic Oligarchy",
    description: [
      "Piltover, also known as the City of Progress, is a thriving, progressive city whose power and influence is on the rise. It is Valoran's cultural center, where art, craftsmanship, trade and innovation walk hand in hand. Its power comes not through military might, but the engines of commerce and forward thinking. ",
      "Piltover, auch bekannt als die Stadt des Fortschritts, ist eine lebende, progressive Stadt, die ihre Macht und ihre Machtinfluenz auf die Rückenlauf. Es ist Valoran's kulturelle Zentrum, wo Kunst, Handwerk, Handel und Innovation zusammenkommen. Ihre Macht kommt nicht durch die Macht der Armee, sondern durch die Motoren der Handel und der Vorwärtskünste.",
      "Piltover, também conhecido como a Cidade do Progresso, é uma cidade prosperada, que está crescendo. É o centro cultural de Valoran, onde arte, artesanato, comércio e inovação se relacionam. Sua força não vem através da força militar, mas os motores de comércio e a mente de frente.",
    ],
    iconUrl: "icons/Piltover_Crest_icon.png",
    imageUrl: "images/Piltover.jpg",
    wallpapers: {
      0: {
        title: "Zindelo's Incognium ",
        url: "regions/Piltover_00.jpg",
      },
      1: {
        title: "Workshops",
        url: "regions/Piltover_01.jpg",
      },
      2: {
        title: "Bluewind Court",
        url: "regions/Piltover_02.jpg",
      },
    },
    champions: {
      0: { name: "Caitlyn" },
      1: { name: "Camille" },
      2: { name: "Ezreal" },
      3: { name: "Heimerdinger" },
      4: { name: "Jayce" },
      5: { name: "Orianna" },
      6: { name: "Seraphine" },
      7: { name: "Vi" },
    },
  },
  {
    id: 6,
    title: "Targon",
    location: "Shurima (West)",
    type: "Tribal Theocracy",
    description: [
      "Like any place of myth, Mount Targon is a beacon to dreamers, madmen and questors of adventure. A mountainous and sparsely inhabited region to the west of Shurima, Targon boasts the tallest peak in Runeterra. Located far from civilization, Mount Targon is all but impossible to reach, save by the most determined pilgrims, chasing some soul-deep yearning to reach its summit. ",
      "Wie jeder Ort von Mythos, Mount Targon ist ein Leuchtturm für den Geist des Abenteuers, der Männer und die Questeure. Eine gebrochene und sparsame Region westlich von Shurima, Targon bietet die höchste Spitze in Runeterra. In ihr liegt vielleicht nur ein paar Menschen, die sich durch die harte Arbeit und die unerlässliche Anstrengung, ihr Ziel zu erreichen, nicht erreichen können. ",
      "Como qualquer lugar de mitologia, Mount Targon é um sinal para os sonhos, os loucos e os questores de aventuras. Uma região montanhosa e esparso ocupada ao oeste de Shurima, Targon oferece a maior montanha de Runeterra. Localizada muito longe da cidade, Mount Targon é tão impossível de atingir, que só é possível através de pessoas determinadas, que procuram algumas alma profunda para chegar à sua cima.",
    ],
    iconUrl: "icons/Mount_Targon_Crest_icon.png",
    imageUrl: "images/Targon.jpg",
    wallpapers: {
      0: {
        title: "Carved into the Mountain",
        url: "regions/Targon_00.jpg",
      },
      1: {
        title: "Skies around mount Targon",
        url: "regions/Targon_01.jpg",
      },
      2: {
        title: "Mount Peak",
        url: "regions/Targon_02.jpg",
      },
    },
    champions: {
      0: { name: "Aphelios" },
      1: { name: "Diana" },
      2: { name: "Leona" },
      3: { name: "Pantheon" },
      4: { name: "Soraka" },
      5: { name: "Taric" },
      6: { name: "Zoe" },
    },
  },
  {
    id: 7,
    title: "Shurima",
    location: "Shurima (Center)",
    type: "Divine Empire",
    description: [
      "The empire of Shurima was once a thriving civilization that spanned a vast desert. After an era of growth and prosperity, the fall fall of its gleaming capital left the empire in ruins. Over millennia, tales of Shurima's glorious city became myth and religion among the descendants of the scattered survivors.",
      "Die Empfängnis von Shurima war einmal eine lebende Kultur, die eine weite Weitenwand spannend erreichte. Nach einer Zeit der Erhöhung und Erfolg, brachte die Sturmfall der glühenden Hauptstadt die Empfängnis in Ruinen. Nach Jahren, die die Geschichte der Empfängnis geschrieben hat, wurde die Geschichte der Empfängnis als Mythos und Religion der verbleibenden Überlebenden verbreitet.",
      "O emperio de Shurima foi uma vez uma cidade prosperada e vasta deserta. Depois de uma época de crescimento e prosperidade, a queda da capital de Shurima deixou o emperio em ruinas. Em vários anos, as legendas de Shurima's gloriosa cidade ficaram como mitologia e religião entre os descendentes dos dispersos sobreviventes.",
    ],
    iconUrl: "icons/Shurima_Crest_icon.png",
    imageUrl: "images/Shurima.jpg",
    wallpapers: {
      0: {
        title: "The Valley of the Song",
        url: "regions/Shurima_00.jpg",
      },
      1: {
        title: "Shurima's Ruins",
        url: "regions/Shurima_01.jpg",
      },
      2: {
        title: "Zoantha Cascade",
        url: "regions/Shurima_02.jpg",
      },
    },
    champions: {
      0: { name: "Akshan" },
      1: { name: "Amumu" },
      2: { name: "Azir" },
      3: { name: "Nasus" },
      4: { name: "Rammus" },
      5: { name: "Renekton" },
      6: { name: "Sivir" },
      7: { name: "Skarner" },
      8: { name: "Taliyah" },
      9: { name: "Xerath" },
    },
  },
  {
    id: 8,
    title: "Ionia",
    location: "Ionia",
    type: "Regional Provinces",
    description: [
      "Ionia, in original Vastayan nomenclature: The First Lands, is a land of unspoiled beauty and natural magic. Its inhabitants, living in scattered settlements across this massive archipelago, are a spiritual people who seek to live in harmony and balance with the world. There are many orders and sects across Ionia, each following their own (often conflicting) paths and ideals.",
      "Ionia, im original Vastayan nomenklatur: Die erste Inseln, Ionia, ist eine Land mit unvergesslicher Schönheit und natürlicher Magie. Die Bevölkerung, die in verschiedenen Städten auf diesem großen Archipelago leben, ist eine spirituelle Menschheit, die sich in Harmonie mit dem Weltraum sucht. Auf Ionia gibt es viele Gliederungen und Sekte, jede folgend ihren eigenen Weg und ihren eigenen Idealen.",
      "Ionia, na nomeclatura original Vastayesa: A primeira terra, Ionia, é um terreno de beleza e magia natural. Seus habitantes, que vivem em pequenas aldeias dispersas nesse vasto archipiélago, são uma população espiritual que busca viver em harmonia com o mundo. Há vários ordens e seitas em Ionia, cada uma seguindo sua própria (possivelmente conflitante) trajetória e ideias.",
    ],
    iconUrl: "icons/Ionia_Crest_icon.png",
    imageUrl: "images/Ionia.jpg",
    champions: {
      0: { name: "Ahri" },
      1: { name: "Akali" },
      2: { name: "Irelia" },
      3: { name: "Ivern" },
      4: { name: "Jhin" },
      5: { name: "Karma" },
      6: { name: "Kayn" },
      7: { name: "Kennen" },
      8: { name: "LeeSin" },
      9: { name: "Lillia" },
      10: { name: "MasterYi" },
      11: { name: "Rakan" },
      12: { name: "Sett" },
      13: { name: "Shen" },
      14: { name: "Syndra" },
      15: { name: "Varus" },
      16: { name: "Wukong" },
      17: { name: "Xayah" },
      18: { name: "Yasuo" },
      19: { name: "Yone" },
      20: { name: "Zed" },
    },
  },
  {
    id: 9,
    title: "Shadow Isles",
    location: "Guardian's Sea",
    type: "Former Meritocracy",
    description: [
      "The land now known as the Shadow Isles was once a beautiful realm, but it was shattered by a magical cataclysm. Black Mist permanently shrouds the isles and the land itself is tainted, corrupted by malevolent sorcery sorcery. Living beings that stand upon the Shadow Isles slowly have their life-force leeched from them, which, in turn, draws the insatiable, predatory spirits of the dead. ",
      "Die Land, die nun als die Schatten Inseln heißt, war einmal ein schönes Land, aber es wurde durch ein magisches Katastrophenfall zerstört. Die schwarze Nebel schleiern die Inseln und das Land selbst ist verderbt, verderbt durch die malevolente Magie. Lebende Wesen, die auf der Schatten Inseln stehen, haben ihre Lebenskraft leicht von ihnen geleitet, welche, in seiner selbst, die insatiable, bewährte Seelen von den Toten abnimmt.",
      "A terra que agora é conhecida como a Ilha Sombria era uma vez um belo reino, mas foi quebrada por um cataclismo mágico. A neve preto cobre a ilha e o próprio terreno é corrompido, corrompido por magia malevola. As criaturas viventes que se encontram na Ilha Sombria se deslocam lentamente e seus corações se levantam, que, em seguida, trazem os insatáveis, espíritos da morte.",
    ],
    iconUrl: "icons/Shadow_Isles_Crest_icon.png",
    imageUrl: "images/Blessed_Isles.jpg",
    champions: {
      0: { name: "Elise" },
      1: { name: "Gwen" },
      2: { name: "Hecarim" },
      3: { name: "Kalista" },
      4: { name: "Karthus" },
      5: { name: "Maokai" },
      6: { name: "Mordekaiser" },
      7: { name: "Thresh" },
      8: { name: "Viego" },
      9: { name: "Yorick" },
    },
  },
  {
    id: 10,
    title: "Bilgewater",
    location: "Guardian's Sea",
    type: "Gang Syndicates",
    description: [
      "Bilgewater is a haven for smugglers, marauders, and the unscrupulous, where fortunes are made and ambitions shattered in the blink of an eye. For those fleeing justice, debt, or persecution, it is a city of new beginnings; no one on the twisted streets of Bilgewater cares about your past. It's a melting pot of cultures, races, and creeds, alive with activity at all hours.",
      "Bilgewater ist ein Paradies für Schmuggler, Plünderer und Skrupellose, wo im Handumdrehen Vermögen gemacht und Ambitionen zerstört werden. Für diejenigen, die vor Gerechtigkeit, Schulden oder Verfolgung fliehen, ist es eine Stadt des Neuanfangs; Niemand auf den verwinkelten Straßen von Bilgewater kümmert sich um deine Vergangenheit. Es ist ein Schmelztiegel von Kulturen, Rassen und Glaubensrichtungen, in dem rund um die Uhr Aktivität herrscht.",
      "Aguas de santina é um ponto de retorno para ladrões, bandidos e o desprezível, onde a fortuna é feita e as ambições quebradas são em instantes. Para aqueles que fugem da justiça, dívida ou procuram a perseguição, é uma cidade de novos inicios; ninguém na cidade de bilgewater se preocupa com sua história. É um pântano de culturas, raças e creeds, vivendo com atividade em todas as horas.",
    ],
    iconUrl: "icons/Bilgewater_Crest_icon.png",
    imageUrl: "images/Bilgewater.jpg",
    champions: {
      0: { name: "Gangplank" },
      1: { name: "Graves" },
      2: { name: "Illaoi" },
      3: { name: "MissFortune" },
      4: { name: "Nautilus" },
      5: { name: "Pyke" },
      6: { name: "TwistedFate" },
    },
  },
  {
    id: 11,
    title: "Ixtal",
    location: "Shurima (East)",
    type: "Mage Autocracy",
    description: [
      "Renowned for its mastery of elemental magic, Ixtal was one of the first independent nations to join the Shuriman empire. In truth, Ixtali culture is much older—part of the great westward diaspora that gave rise to civilizations including the Buhru, magnificent Helia, and the ascetics of Targon—and it is likely they played a significant role in the creation of the first Ascended.",
      "Berühmt für seine Beherrschung der Elementarmagie, war Ixtal einer der ersten unabhängigen Nationen, die die Shuriman-Imperium beitragen. In wahrheit ist die Ixtalischen Kultur viel älter—Teil der großen Westwälder, die die Buhru, die wunderschöne Helia und die ausgebildeten Astrale erzeugten, und die wahrscheinlich eine wichtige Rolle in der Herstellung der ersten Aufgestiegten spielten. ",
      "Conhecida por sua maestria em magia elemental, Ixtal foi uma das primeiras nações independentes a se unir ao império Shuriman. Em verdade, a cultura Ixtali é muito mais antiga—parte da grande diáspora oriental que gerou as civilizações incluindo a Buhru, a magnífica Helia e os ascetos de Targon—e provavelmente participaram de uma importante função na criação da primeira Ascensão.",
    ],
    iconUrl: "icons/Ixtal_Crest_icon.png",
    imageUrl: "images/Ixtal.jpg",
    champions: {
      0: { name: "Malphite" },
      1: { name: "Neeko" },
      2: { name: "Nidalee" },
      3: { name: "Qiyana" },
      4: { name: "Rengar" },
      5: { name: "Zyra" },
    },
  },
  {
    id: 12,
    title: "Bandle City",
    location: "Location unkown",
    description: [
      "Opinions differ as to where exactly the home of the yordles is to be found, though a handful of mortals claim to have traveled unseen pathways to a land of curious enchantment beyond the material realm. They tell of a place of unfettered magic, where the foolhardy can be led astray by myriad wonders, and end up lost in a dream...",
      "Wo genau, darüber gehen die Meinungen auseinander wie die Heimat der Yordle woanders liegt, ist nicht bekannt, aber ein paar Menschen sagen, dass sie über unaufhaltsame Wege in einem Land der wunderbaren Zauber liegen. Sie sagen von einem Ort, an dem der Frechheit die Hand nicht gebunden ist, und wo sich der Verrückte in einem Traum befindet...",
      "Opiniões diferem sobre onde está exatamente a casa dos yordles, mas um pouco de humanos dizem que já passaram por caminhos inexplorados para um mundo de encantamento curioso além do reino material. Eles dizem de um lugar onde o louco pode ser guiado por muitas maravilhas, e ficar perdido em um sonho...",
    ],
    iconUrl: "icons/Bandle_City_Crest_icon.png",
    imageUrl: "images/Bandle_City.jpg",
    champions: {
      0: { name: "Corki" },
      1: { name: "Lulu" },
      2: { name: "Rumble" },
      3: { name: "Teemo" },
      4: { name: "Tristana" },
      5: { name: "Veigar" },
      6: { name: "Vex" },
      7: { name: "Yuumi" },
    },
  },
  {
    id: 13,
    title: "The Void",
    location: "Location Unknown",
    description: [
      "Screaming into existence with the birth of the universe, the Void is a manifestation of the unknowable nothingness that lies beyond. It is a force of insatiable hunger, waiting through the eons until its masters, the mysterious Watchers, mark the final time of undoing. To be a mortal touched by this power is to suffer an agonizing glimpse of eternal unreality, enough to shatter even the strongest mind. Denizens of the Void realm itself are construct-creatures, often of only limited sentience, but tasked with a singular purpose - to usher in total oblivion across Runeterra.",
      "Schreiend ins Leben gerufen mit der Geburt des Universums, ist der Void eine Manifestation der unbekannten Nichts, das außerhalb der Grenzen liegt. Es ist eine Kraft der unendlichen Hunger, die sich über die Jahre wartet, bis seine Meister, die mysteriösen Beobachter, die letzte Zeit markieren, um die Zerstörung zu beenden. Um ein Mensch zu sein, der von dieser Kraft getragen wird, ist es zu leiden, einen überwältigen Blick auf ewiges Unrecht, um auch die stärkste Körper zu zerstören. Die Bewohner des Void-Realms selbst sind Konstrukt-Kreaturen, oft nur eingeschränkt gedanklich, aber mit einer einzigen Aufgabe - die Zerstörung von totalem Unrecht über Runeterra zu bringen.",
      "Ao criar o universo, o vazio se torna uma manifestação da nada desconhecido, que está fora dos limites. É uma força de fome insaciável, esperando pelos eons até que seus mestres, os mistériosos observadores, marque a última vez de desfazer. Para ser um mortal tocado por essa força é para sofrer um olhar agonizante para o eterno desconhecido, suficiente para desfazer ainda o mais forte cérebro. Os desaparecidos do reino do vazio são criaturas construídas, em geral de pouca sentidos, mas obrigados a uma única missão - a trazer total oblício por toda Runeterra.",
    ],
    iconUrl: "icons/Void_Crest_icon.png",
    imageUrl: "images/Void.jpg",
    champions: {
      0: { name: "Chogath" },
      1: { name: "Kaisa" },
      2: { name: "Kassadin" },
      3: { name: "Khazix" },
      4: { name: "KogMaw" },
      5: { name: "Malzahar" },
      6: { name: "RekSai" },
      7: { name: "Velkoz" },
    },
  },
];
